title: CV Arxiv Daily
description: Automatically Update CV Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/theneao/CV-SAR-Seg-arxiv-daily
  another_url: https://github.com/theneao/CV-SAR-Seg-arxiv-daily

## add remote theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# minima:
skin: dark
social_links:
  github: theneao

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
